### ISSUE TITLE
Indexing Output  Report the following errors 

### ISSUE THREAD

**Issue by lonnys** [severian42/GraphRAG-Local-UI#14]
🚀 Reading settings from /Users/lonny/VSCODE/GraphRAG-Ollama-UI/ragtest/settings.yaml

/Users/lonny/VSCODE/GraphRAG-Ollama-UI/.conda/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.

  return bound(*args, **kwds)

Name: numpy
Version: 1.25.2

**Comment by lonnys** [comment]
Friends who have passed the debugging, may I ask which version of Python did everyone use?

**Comment by severian42** [comment]
Hey! Sorry for the late response. I use 3.11 for this but others have used 3.10 and it seemed to work. Let me know if you are still encountering issues and Ill see if I can help out
