### ISSUE TITLE
version conflict of aiofile

### ISSUE THREAD

**Issue by haohaotian1011** [severian42/GraphRAG-Local-UI#17]
when I execute "pip install -r requirements.txt" , I find a problem as the following:

Warning!!! Possibly conflicting dependencies found:
* graphrag==0.1.1
 - aiofiles [required: >=24.1.0,<25.0.0, installed: 23.2.1]
gradio==4.38.1
├── aiofiles [required: >=22.0,<24.0, installed: 23.2.1]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
graphrag 0.1.1 requires aiofiles<25.0.0,>=24.1.0, but you have aiofiles 23.2.1 which is incompatible.

I use conda with python==3.11.0 in my environment.

So how can I resolve it? Has anyone encountered the same installation issue as me?

**Comment by severian42** [comment]
Hey! Thanks for catching this. I haven't run into this so it might just be a matter of getting rid of the specific versions for aiofiles and see if that works. Also, try deleting your pycache and relaunching the app before reinstalling. That can help give you a clean start
