### ISSUE TITLE
Error: model "mistral:7b" not found, try pulling it first

### ISSUE THREAD

**Issue by vinhqdang** [severian42/GraphRAG-Local-UI#18]
Hello

Thanks for the code, it seems great.

I have just pulled your code and try to run.

I already called
"ollama run mistral" on my local Mac and it seems to work.

<img width="539" alt="image" src="https://github.com/user-attachments/assets/90150913-9f63-477b-ae6c-b109eb07bf6e">

But when I tried to chat on the gradio UI I have this error

<img width="518" alt="image" src="https://github.com/user-attachments/assets/e27bae79-b63f-4124-a2db-14bc479dd3b3">

Do you have any suggestion I can fix?

**Comment by severian42** [comment]
Hey! If you edit the model name to reflect the one you pulled, i.e. `mistral` it should work for you just fine. The `mistral:7b` is just how it's uniquely named on my local system

**Comment by canytam-krystal** [comment]
I have similar problem and modified the model setting but the system still ask for mistral:7b.
![Screenshot from 2024-07-18 10-17-49](https://github.com/user-attachments/assets/d780d821-b360-4a91-9d57-dc72ee48f0ce)

**Comment by severian42** [comment]
So I think I found the issue with the current version. Right under the chat window, I have the Model Parameters dropdown menu and from there you can select the model. This menu selection overrides the setting.yaml input. If you use the drop down and select the model it should update your setting.yaml, if not just make sure the two match and it'll work for you
