### ISSUE TITLE
Query Type "global" not working

### ISSUE THREAD

**Issue by slutifsh99** [severian42/GraphRAG-Local-UI#19]
After generating the graph using the indexing process, how can I ensure that the LLM  uses this indexed information to answer questions? Currently, it seems like the LLM is not leveraging the indexed data as expected.

Details

I've completed the following steps:

Indexed the data successfully.
Generated the graph using the indexed data.
Configured the Query Type to "global" expecting it to use the indexed information.
Despite these steps, the responses to queries do not appear to be using the indexed data, and the results are similar to those from "direct" queries.

**Comment by severian42** [comment]
Hey! The way the GraphRAG library wants to work is to have your selected output folder initialized first, and then it'll use those contents. I will be releasing a quick tutorial vid hopefully today with the major update.

How to query the generated graph:

-If you are able to run the Indexing with no errors you will end up with the full output files.
-Once you have those, you will need to initialize the folder within the Index Management tab.
-Once you have initialized (should be 20 items in total) it will make the graph available to query with the LLM

**Comment by isaidnoagain** [comment]
Having same issue, looking forward to your vid!

**Comment by OKC13** [comment]
Having same issue, looking forward to your vid!


![image](https://github.com/user-attachments/assets/967cd2e1-1d94-4a50-9e76-6b46bae21c04)

**Comment by Ikaros-521** [comment]
same +1
