### ISSUE TITLE
An error occurred: Direct chat failed: Chat request failed: Connection error.

### ISSUE THREAD

**Issue by Essence9999** [severian42/GraphRAG-Local-UI#37]
The lastest version
![image](https://github.com/user-attachments/assets/fbe4c029-3cf9-4ea6-8f46-edd18367a865)

![image](https://github.com/user-attachments/assets/f0db64a7-7240-417d-a5b9-28245e390c68)

**Comment by severian42** [comment]
Hmmmm I'm not sure why you wouldn't be able to connect. The provider routing is using the OpenAI framework and exposing it for OpenAI compatibility, so it should be able to connect you to any base URL. I've really only tested it using local LLM set-ups though myself

**Comment by Essence9999** [comment]
> Hmmmm I'm not sure why you wouldn't be able to connect. The provider routing is using the OpenAI framework and exposing it for OpenAI compatibility, so it should be able to connect you to any base URL. I've really only tested it using local LLM set-ups though myself

Get the model is okay
![image](https://github.com/user-attachments/assets/a1b06c45-ac3f-4da7-9ce5-7e980530aee9)
But chat is wrong
![image](https://github.com/user-attachments/assets/d937078d-cca4-4b2c-bb7d-37c368b0820b)

**Comment by Essence9999** [comment]
sudo ufw allow 11434
solved my problem
