### ISSUE TITLE
Can't  find DDG api wrapper

### ISSUE THREAD

**Issue by lawfordp2017** [severian42/GraphRAG-Local-UI#57]
I'm getting this message on startup:

Traceback (most recent call last):
  File "...../GraphRAG-Local-UI/api.py", line 21, in <module>
    from web import DuckDuckGoSearchAPIWrapper
ModuleNotFoundError: No module named 'web'

**Comment by severian42** [comment]
Ah!!! Thank you so much for catching this! Uploading the web.py file right now. Got lost in the process of reorganizing
