### ISSUE TITLE
port 11435 used for ?

### ISSUE THREAD

**Issue by Tovi163** [severian42/GraphRAG-Local-UI#68]
python embedding_proxy.py --port 11435 --host http://localhost:11434

**Comment by severian42** [comment]
This is to host a separate embeddings for Ollama since their API is strictly /api/embeddings

**Comment by Tovi163** [comment]
> This is to host a separate embeddings for Ollama since their API is strictly /api/embeddings

port 11435 used for ? I do not see anywhere use the port of 11435

**Comment by havvk** [comment]
> > This is to host a separate embeddings for Ollama since their API is strictly /api/embeddings
> 
> port 11435 used for ? I do not see anywhere use the port of 11435 @severian42

You need it only for embeddings with Ollama.
It will not be used when you do embeddings through openai API.

**Comment by Tovi163** [comment]
> This is to host a separate embeddings for Ollama since their API is strictly /api/embeddings

Get it, thanks again
